### ISSUE TITLE
As a MLOps engineer I would like to use ACM GitOps tools to deploy my model at the near edge. 

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/ai-edge#10]
- [ ] As a MLOps engineer I would like to use git as my source of truth for the deployment of my containerized model, so I can manage its lifecycle using a GitOps approach.
- [ ] As a MLOps engineer I would like that once my definition of the containerized model is defined in Git, ACM reconciles the desired state with my cluster at the edge. So I have a fully automated deployment mechanism.
- [ ] As a MLOps engineer I would like to deploy my containerized model to the near edge using ACM pull model, so I can meet the security requirement about the connection to a hub/core data center. 
- [ ] As a MLOps engineer I would like to see the topology of my applications installed at the edge, so I can have more control over what containerized models are deployed in which edge location.
- [ ]  As a MLOps engineer I would also like to manage with ACM the infrastructure needed to deploy models so I can have a single management tool for the whole solution.

**Comment by LaVLaS** [comment]
Closing this as this task is made redundant by #11 tracker and #21 and #22 are standalone tasks that don't need to be nested under this tracker also
